# Server Configuration
server.port=8080
server.servlet.context-path=/restaurant
server.error.whitelabel.enabled=false

# Spring Profiles
spring.profiles.active=prod

# Application Name
spring.application.name=Take Order Web Application

# Logging
logging.level.root=INFO
logging.level.com.restaurant=DEBUG